apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  namespace: dev
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/tmp"
