apiVersion: v1
kind: Service
metadata:
  name:  postgres-cluster-ip-service
  namespace: dev
spec:
  selector:
    component: postgres
  type: ClusterIP
  ports:
    - port:  5432
      targetPort:  5432